<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Idea;

/**
 * IdeaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IdeaRepository extends \Doctrine\ORM\EntityRepository
{
    public function getIdee(){
        $em = $this->getEntityManager();
        $queryBuilder = $em->createQueryBuilder();
        $queryBuilder->select(['idee'])
            ->from(Idea::class, 'idee')
            ->where('idee.isPublished=1')
            ->andWhere('idee.isPublished<= :date_now')
            ->orderBy('idee.dateCreated', 'DESC');
        $query = $queryBuilder->getQuery();
        $query->setParameter('date_now', date('Y-m-d H:i:s'));
        return $query->getResult();
    }

    public function getIdeeDetail($id){
        $em = $this->getEntityManager();
        $queryBuilder = $em->createQueryBuilder();
        $queryBuilder->select(['idee'])
            ->from('AppBundle:Idea', 'idee')
            ->where("idee.id=$id");
        return $queryBuilder->getQuery()->getResult();
    }

    public function updateIdee(){
        $em = $this->getEntityManager();
        $queryBuilder = $em->createQueryBuilder();

    }
}
