# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        users_login:
            entity:
                class: AppBundle\Entity\User #ou AppBundle:user
                property: pseudo #champs sur lequel l'authentification sera faite

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER


    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: true
            provider: users_login

            form_login:
                login_path: /user/login
                check_path: /user/login

            logout:
                path: /user/logout
                target: /
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~

    access_control:
        - {path: ^/idee/create, roles: ROLE_USER} #methode 2 : pour reguler l'accès
        - {path: ^/idee/delete, roles: ROLE_USER}
        - {path: ^/admin/category/create, roles: ROLE_USER}
        - {path: ^/admin/category/update, roles: ROLE_USER}
        - {path: ^/admin/category/delete, roles: ROLE_USER}